### DISCUSSION TITLE
Getting a "session reuse required" error. Not sure what to do.

### DISCUSSION THREAD

**Discussion by cvsickle** [crazy-max/ftpgrab#386] [Q&A]
Trying to use FTPgrab to automatically pull finished timelapse videos from my Bambu Lab X1 Carbon printer. I currently use FileZilla to transfer these videos off the printer (using ftps). When I try to use FTPGrab to connect, it's successfully logging in, but gets an error when it tries to create the directory listing:

`522 SSL connection failed: session reuse required`

Not sure if this is a configuration issue on my end, or if this indicates a server option is enabled that FTPgrab isn't setup to handle. Any help would be appreciated.

Here's my config:

```
db:
  path: ftpgrab.db

server:
  ftp:
    host: {ip}
    port: {port}
    username: bblp
    password: {accesscode}
    sources:
      - /timelapse
    timeout: 30s
    disableUTF8: false
    disableEPSV: false
    disableMLSD: false
    escapeRegexpMeta: false
    tls: true
    insecureSkipVerify: true
    logTrace: true

download:
  output: /download
  uid: {uid}
  gid: {gid}
  chmodFile: 0o644
  chmodDir: 0o755
  include:
    - \.mp4
  exclude:
    - \.nfo$
    - \.video
    - thumbnail
  since: 2024-10-29T00:00:00Z
  retry: 3
  hideSkipped: false
  tempFirst: false
  createBaseDir: false
```

And here's my trace log:

```
Sat, 02 Nov 2024 23:18:31 UTC INF Next run in 28 seconds 802 milliseconds (2024-11-02 23:19:00 +0000 UTC)
Sat, 02 Nov 2024 23:19:00 UTC WRN No notifier available
Sat, 02 Nov 2024 23:19:00 UTC DBG 0 entries found in database
Sat, 02 Nov 2024 23:19:00 UTC DBG 220 (vsFTPd 3.0.3)
Sat, 02 Nov 2024 23:19:00 UTC DBG USER {user}
Sat, 02 Nov 2024 23:19:00 UTC DBG 331 Please specify the password.
Sat, 02 Nov 2024 23:19:00 UTC DBG PASS {accesscode}
Sat, 02 Nov 2024 23:19:00 UTC DBG 230 Login successful.
Sat, 02 Nov 2024 23:19:00 UTC DBG FEAT
Sat, 02 Nov 2024 23:19:00 UTC DBG 211-Features:
Sat, 02 Nov 2024 23:19:00 UTC DBG AUTH TLS
Sat, 02 Nov 2024 23:19:00 UTC DBG EPRT
Sat, 02 Nov 2024 23:19:00 UTC DBG EPSV
Sat, 02 Nov 2024 23:19:00 UTC DBG MDTM
Sat, 02 Nov 2024 23:19:00 UTC DBG PASV
Sat, 02 Nov 2024 23:19:00 UTC DBG PBSZ
Sat, 02 Nov 2024 23:19:00 UTC DBG PROT
Sat, 02 Nov 2024 23:19:00 UTC DBG REST STREAM
Sat, 02 Nov 2024 23:19:00 UTC DBG SIZE
Sat, 02 Nov 2024 23:19:00 UTC DBG TVFS
Sat, 02 Nov 2024 23:19:00 UTC DBG UTF8
Sat, 02 Nov 2024 23:19:00 UTC DBG 211 End
Sat, 02 Nov 2024 23:19:00 UTC DBG TYPE I
Sat, 02 Nov 2024 23:19:00 UTC DBG 200 Switching to Binary mode.
Sat, 02 Nov 2024 23:19:00 UTC DBG OPTS UTF8 ON
Sat, 02 Nov 2024 23:19:00 UTC DBG 200 Always in UTF8 mode.
Sat, 02 Nov 2024 23:19:00 UTC DBG PBSZ 0
Sat, 02 Nov 2024 23:19:00 UTC DBG 200 PBSZ set to 0.
Sat, 02 Nov 2024 23:19:00 UTC DBG PROT P
Sat, 02 Nov 2024 23:19:00 UTC DBG 200 PROT now Private.
Sat, 02 Nov 2024 23:19:00 UTC DBG Listing files source=/timelapse
Sat, 02 Nov 2024 23:19:00 UTC DBG EPSV
Sat, 02 Nov 2024 23:19:00 UTC DBG 229 Entering Extended Passive Mode (|||50011|)
Sat, 02 Nov 2024 23:19:00 UTC DBG LIST /timelapse
Sat, 02 Nov 2024 23:19:00 UTC DBG 150 Here comes the directory listing.
Sat, 02 Nov 2024 23:19:00 UTC DBG 522 SSL connection failed: session reuse required
Sat, 02 Nov 2024 23:19:00 UTC ERR Cannot read directory /timelapse error="1 error occurred:\n\t* 522 SSL connection failed: session reuse required\n\n" source=/timelapse
Sat, 02 Nov 2024 23:19:00 UTC WRN No file found from the provided sources
Sat, 02 Nov 2024 23:19:00 UTC DBG QUIT
Sat, 02 Nov 2024 23:19:00 UTC INF Next run in 29 seconds 972 milliseconds (2024-11-02 23:19:30 +0000 UTC)
Sat, 02 Nov 2024 23:19:16 UTC DBG QUIT
Sat, 02 Nov 2024 23:19:16 UTC WRN Cannot close server connection error="2 errors occurred:\n\t* use of closed network connection\n\t* use of closed network connection\n\n"
Sat, 02 Nov 2024 23:19:16 UTC WRN Caught signal terminated
```
