### ISSUE TITLE
Folder with "." are Ignored

### ISSUE THREAD

**Issue by drag0n141** [crazy-max/ftpgrab#201]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/crazy-max/ftpgrab/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

Hi, all Folders with "." in Name are ignored. And not appered in LOG i can only see the Folder with "FTPGRAB_SERVER_FTP_LOGTRACE=true". I think the Problem is that is escapes the "." with \ and then the Folder is not reachable.

### Expected behaviour

Download the folders with "." in name

### Actual behaviour

Ignores the folders with "." in name

### Steps to reproduce

Folder on FTP with "." in Name

### Version

* FTPGrab version (5.0.0): 7.6.0
* Platform (windows/linux/freebsd/macos): Linux Docker

### Configuration

```yaml
db:
  path: ftpgrab.db

server:
  ftp:
    host:
    port:
    username:
    password:
    sources:
      - /PS4
    timeout: 5s
    tls: false
    insecureSkipVerify: false
    logTrace: false

download:
  output: /download
  uid: 1000
  gid: 1000
  chmodFile: 0644
  chmodDir: 0755
  exclude:
    - \.nfo$
    - \.jpg$
  since: 0001-01-01T00:00:00Z
  retry: 5
  hideSkipped: false
  createBaseDir: true

notif:
  mail:
    host:
    port: 587
    username:
    password:
    ssl: false
    insecureSkipVerify: false
    from:
    to:
```

### Logs

Thu, 29 Jul 2021 13:23:08 CEST DBG EPSV
Thu, 29 Jul 2021 13:23:08 CEST DBG 229 Entering Extended Passive Mode (|||36687|)
Thu, 29 Jul 2021 13:23:08 CEST DBG LIST /PS4/Arc_of_Alchemist_Update_v1\\.01_CHT_PS4-MOEMOE
Thu, 29 Jul 2021 13:23:08 CEST DBG 150 Opening BINARY mode data connection for directory listing.
Thu, 29 Jul 2021 13:23:08 CEST DBG 226- [Ul: 0.0MB] [Dl: 1410855.1MB] [Speed: 0.00K/s]
226  [Section: DEFAULT] [Credits: 14.6MB] [Ratio: UL&DL: Unlimited]
