### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by amanullahtanweer** [crazy-max/ftpgrab#260]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/crazy-max/ftpgrab/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I am trying to connect a ftp server which is using TLS self signed certificate and i am getting this error

### Expected behaviour

Should connect to ftp normally

### Actual behaviour

```
Thu, 08 Sep 2022 08:45:35 UTC INF Starting FTPGrab 6.3.0
Thu, 08 Sep 2022 08:45:35 UTC FTL Cannot connect to server error="tls: first record does not look like a TLS handshake"
```

### Steps to reproduce

`/usr/local/bin/ftpgrab --config /etc/ftpgrab/ftpgrab.yml`

### Version

FTPGrab "Version": "6.3.0"
Linux Alma-85-amd64-base 4.18.0-348.12.2.el8_5.x86_64 #1 SMP Wed Jan 19 14:35:04 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

### Configuration

```yaml
server:
  type: ftp
  ftp:
    host: xxxxxxx
    port: 21
    username: xxxxx
    password: xxxx
    sources:
      - /accounts/
      - /all/
    timeout: 5s
    disable_epsv: false
    tls: true
    insecure_skip_verify: false
    log_trace: true
download:
  output: /home/downloads/
  uid:
  gid:
  chmod_file: 0644
  chmod_dir: 0755
  include:
  exclude:
  since: 2022-04-1T00:00:00Z
  retry: 3
  hide_skipped: false
  create_basedir: false
```

### Logs

```
Thu, 08 Sep 2022 08:50:55 UTC INF Starting FTPGrab 6.3.0
Thu, 08 Sep 2022 08:50:55 UTC DBG {
  "Flags": {
    "Cfgfile": "/etc/ftpgrab/ftpgrab.yml",
    "Schedule": "",
    "Timezone": "UTC",
    "LogLevel": "debug",
    "LogJson": false,
    "LogFile": ""
  },
  "App": {
    "ID": "ftpgrab",
    "Name": "FTPGrab",
    "Desc": "Grab your files periodically from a remote FTP or SFTP server easily",
    "URL": "https://ftpgrab.github.io",
    "Author": "CrazyMax",
    "Version": "6.3.0"
  },
  "Server": {
    "Type": "ftp",
    "FTP": {
      "Host": "ftp1001.sipnavigator.com",
      "Port": 21,
      "Username": "********",
      "Password": "********",
      "Sources": [
        "/accounts/",
        "/all/"
      ],
      "Timeout": 5000000000,
      "DisableEPSV": false,
      "TLS": true,
      "InsecureSkipVerify": false,
      "LogTrace": true
    },
    "SFTP": {
      "Host": "",
      "Port": 22,
      "Username": "********",
      "Password": "********",
      "Key": "********",
      "Sources": null,
      "Timeout": 30,
      "MaxPacketSize": 32768
    }
  },
  "Db": {
    "Enable": true,
    "Path": "ftpgrab.db"
  },
  "Download": {
    "Output": "/home/deploy/sipnav/downloads",
    "UID": 0,
    "GID": 0,
    "ChmodFile": 420,
    "ChmodDir": 493,
    "Include": null,
    "Exclude": null,
    "Since": "0001-01-01T00:00:00Z",
    "Retry": 3,
    "HideSkipped": false,
    "CreateBasedir": false
  },
  "Notif": {
    "Mail": {
      "Enable": false,
      "Host": "localhost",
      "Port": 25,
      "SSL": false,
      "InsecureSkipVerify": false,
      "Username": "********",
      "Password": "********",
      "From": "",
      "To": ""
    },
    "Slack": {
      "Enable": false,
      "WebhookURL": ""
    },
    "Webhook": {
      "Enable": false,
      "Endpoint": "",
      "Method": "GET",
      "Headers": null,
      "Timeout": 10
    }
  }
}
Thu, 08 Sep 2022 08:50:56 UTC FTL Cannot connect to server error="tls: first record does not look like a TLS handshake"
```
