### ISSUE TITLE
File permissions not created properly?

### ISSUE THREAD

**Issue by anonmily** [crazy-max/ftpgrab#267]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/crazy-max/ftpgrab/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

For some reason, it seems like the file permissions set in the download section of the config isn't being set properly... The file permissions I've set are 1775, but for some reason, the permissions that I end up with in my files is `--wxr-xwx`. The uid and guid are set properly, but it's just that the permissions are all strange. 

I'm running ftpgrab via docker. Here's the docker compose file I'm running with at the moment. I ended up trying to add a "rw" option to the volume mount in attempt to fix the permissions issue, but it doesn't seem to be a problem with docker. Ftpgrab seems to remove read permissions from my mounted volume directory every time it runs.

```
version: "3.5"
services:
  ftpgrab:
    image: crazymax/ftpgrab:latest
    container_name: ftpgrab
    volumes:
      - "./db:/db:rw"
      - "/home/dev/Pictures/downloads:/download:rw"
      - "./ftpgrab.yml:/ftpgrab.yml:ro"
    environment:
      - "TZ=America/Los_Angeles"
      - "SCHEDULE=*/30 * * * *"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    restart: always
```

### Expected behaviour

The mounted volume folder permissions remain untouched or is set as `rwxrwsr-x` (1755).  All files and directories downloaded by FTP grab should be set to 1755. 

### Actual behaviour

Permissions are changed on all files that are updated during a run of ftpgrab to `--wxr-xwx`

### Steps to reproduce

Run ftpgrab via docker using the docker compose file and ftpgrab settings: `docker compose up -d`

### Version

* FTPGrab version (latest):
* Platform: Linux/Ubuntu 22.1:
* System info (type `uname -a`): Linux dev1 5.19.0-23-generic #24-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 14 15:39:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Remote FTP (Pure-FTPd) or SFTP (OpenSSH) server: SFTP

### Configuration

```yaml
db:
  path: /db/ftpgrab.db

server:
  sftp:
    host: <host>
    port: 22
    username: <username>
    password: <password>
    sources:
      - /images

.download:
  output: /download
  uid: 1001
  gid: 1001
  chmodFile: 1775
  chmodDir: 1775
  include:
    - (\w+).jpg
  retry: 3
  hideSkipped: true
```

### Logs

N/A
